# **Setup script environment**
Import external libraries:

In [1]:
import pandas as pd # imports the 'pandas' library for use in this script and assigns it the nickname 'pd'

*This block is only needed when using Google Colab to read files in google drive.*

*Not required if running script on other platforms.*

In [2]:
# only needed to read files from Google Drive for Google Colab
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

# **Using pandas**
Load data from file:

In [3]:
df = pd.read_csv('/content/gdrive/MyDrive/datacon_hands_on/sales.csv') # loading the data from sales.csv into the DataFrame object
# df = pd.read_csv('/PATH/TO/sales.csv') # use this instead if working offline
df.index = df.index + 1

Some DataFrame functions built into pandas:

In [4]:
df.head()

,SalesID,SalesDate,OrderID,CustomerID,SalesPersonID,ProductID,Quantity,Sales,StoreID,OrderStatus
1,112,1/1/2020,13749,37,9,70,7,226.0,9,Incomplete
2,113,1/1/2020,13757,59,4,36,37,326.1,7,Pending
3,114,1/1/2020,13757,59,4,40,19,422.9,7,Incomplete
4,115,1/1/2020,13767,3,9,11,60,1683.8,7,Pending
5,116,1/1/2020,13767,3,9,40,12,230.9,7,Incomplete

In [5]:
l = len(df)
print(l)

8498

In [6]:
df['SalesID'] # get SalesID column

1        112
2        113
3        114
4        115
5        116
        ...
8494    2843
8495    2677
8496    2844
8497    2678
8498    2845
Name: SalesID, Length: 8498, dtype: int64

In [7]:
df.loc[1] # get 1st row

SalesID                 112
SalesDate          1/1/2020
OrderID               13749
CustomerID               37
SalesPersonID             9
ProductID                70
Quantity                  7
Sales                 226.0
StoreID                   9
OrderStatus      Incomplete
Name: 1, dtype: object

In [8]:
df.loc[1]['SalesID'] # get 1st row of SalesID column

112

In [9]:
column_names = list(df)
print(column_names)

['SalesID', 'SalesDate', 'OrderID', 'CustomerID', 'SalesPersonID', 'ProductID', 'Quantity', 'Sales', 'StoreID', 'OrderStatus']

# **Data quality check functions**
Each function checks the values in 1 row against 1 validation rule:

In [10]:
def check_cannot_be_blank (df, column_name): # returns true if column_name contains no blanks
  column_values = df[column_name]
  for column_value in column_values:
    if pd.isna(column_value): # pd.isna(column_value) returns False if column_value is blank
      return False
  return True

In [11]:
print(check_cannot_be_blank(df, 'SalesID'))

True

Use a *for* loop to check all columns:

In [12]:
for column_name in column_names:
  print(check_cannot_be_blank(df, column_name))

True
True
True
True
True
True
True
True
True
True

Define all the individual validation rule check functions:

In [13]:
from collections import defaultdict
import math

def check_unique_values (df, column_name): # returns true if all values in column_name are unique (no duplicates)
  value_occurence_count = defaultdict(int) # a defaultdict is a dictionary with a default value - defaultdict(int) defaults to 0 for keys not yet added to the dictionary
  for index in range(1,l + 1): # remember l is len(df)
    value = df.loc[index][column_name]
    value_occurence_count[value] += 1
    if value_occurence_count[value] > 1:
      return False
  return True

def check_type (df, column_name, type_specified): # returns true if all values in column_name are integers
  for value in df[column_name]:
    if not isinstance(value, type_specified):
      return False
  return True

def check_within_numerical_range (df, column_name, lower_bound = - math.inf, upper_bound = math.inf): # returns true if all values in column_name are between lower_bound and upper_bound exclusive
  for value in df[column_name]:
    if value >= upper_bound or value <= lower_bound: # note that here we are using numerical operators -
      return False
  return True

def is_intable (s):
  try:
    int(s)
  except:
    return False
  return True

def is_alphabetical (s):
  for char in s:
    if ord(char) not in range(97,123) and ord(char) not in range(65,91):
      return False
  return True

def check_data_format (df, column_name, character_type, pieces_max_lengths): # returns true if all values in column_name comply with data format specified
  column_values = df[column_name]
  match character_type:
    case 'N':
      if len(pieces_max_lengths) == 2: # data format is N(p,q)
        for value in df[column_name]:
          val_str = str(value)
          val_str_pieces = val_str.split('.')
          complies = is_intable(val_str_pieces[0]) and is_intable(val_str_pieces[1]) and len(val_str_pieces[0]) <= pieces_max_lengths[0] and len(val_str_pieces[1]) <= pieces_max_lengths[1]
          if not complies:
            return False
        return True
      elif len(pieces_max_lengths) == 1: # data format is N(p)
        for value in df[column_name]:
          complies = is_intable(value) and len(str(value)) <= pieces_max_lengths[0]
          if not complies:
            return False
        return True
    case 'A': # data format is A(p)
      for value in df[column_name]:
        complies = is_alphabetical(value) and len(value) <= pieces_max_lengths[0]
        if not complies:
          return False
      return True
    case 'X': # data format is X(p)
      for value in df[column_name]:
        complies = len(value) <= pieces_max_lengths[0]
        if not complies:
          return False
      return True

def check_date_format_dmyyyy (df, column_name): # returns true if all values in column_name follow the date format d/m/yyyy
  for value in df[column_name]:
    value_split = value.split('/') # split each value into 3 parts to assess individually
    if int(value_split[0]) < 0 or int(value_split[0]) > 31: # reject if date is not int or date < 0 or date > 31
      return False
    if int(value_split[1]) < 0 or int(value_split[1]) > 12: # reject if month is not int or month < 0 or month > 12
      return False
    if len(value_split[2]) != 4 or not is_intable(value_split[2]): # reject if year is not int or year is not 4 digits
      return False
  return True

Run the defined functions on the respective columns, and print the results:

In [14]:
# check SalesID column
print('check SalesID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'SalesID', 'N', [4])))
print('Unique values: ' + str(check_unique_values(df, 'SalesID')))
print('Is integer: ' + str(check_type(df, 'SalesID', int)))
print('> 0: ' + str(check_within_numerical_range(df, 'SalesID', lower_bound = 0)))
print('\n')

# check SalesDate column
print('check SalesDate column')
print('====')
print('Data format: ' + str(check_data_format(df, 'SalesDate', 'X', [10])))
print('Date format: ' + str(check_date_format_dmyyyy(df, 'SalesDate')))
print('\n')

# check OrderID column
print('check OrderID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'OrderID', 'N', [5])))
print('Is integer: ' + str(check_type(df, 'OrderID', int)))
print('>0: ' + str(check_within_numerical_range(df, 'OrderID', lower_bound = 0)))
print('\n')

# check CustomerID column
print('check CustomerID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'CustomerID', 'N', [3])))
print('Is integer: ' + str(check_type(df, 'CustomerID', int)))
print('> 0: ' + str(check_within_numerical_range(df, 'CustomerID', lower_bound = 0)))
print('\n')

# check SalesPersonID column
print('check SalesPersonID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'SalesPersonID', 'N', [1])))
print('Is integer: ' + str(check_type(df, 'SalesPersonID', int)))
print('> 0: ' + str(check_within_numerical_range(df, 'SalesPersonID', lower_bound = 0)))
print('\n')

# check ProductID column
print('check ProductID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'ProductID', 'N', [2])))
print('Is integer: ' + str(check_type(df, 'ProductID', int)))
print('> 0: ' + str(check_within_numerical_range(df, 'ProductID', lower_bound = 0)))
print('\n')

# check Quantity column
print('check Quantity column')
print('====')
print('Data format: ' + str(check_data_format(df, 'Quantity', 'N', [4])))
print('Is integer: ' + str(check_type(df, 'Quantity', int)))
print('> 0: ' + str(check_within_numerical_range(df, 'Quantity', lower_bound = 0)))
print('\n')

# check Sales column
print('check Sales column')
print('====')
print('Data format: ' + str(check_data_format(df, 'Sales', 'N', [10, 2])))
print('Is float: ' + str(check_type(df, 'Sales', float)))
print('>= 0: ' + str(check_within_numerical_range(df, 'Sales', lower_bound = -1)))
print('\n')

# check StoreID column
print('check StoreID column')
print('====')
print('Data format: ' + str(check_data_format(df, 'StoreID', 'N', [1])))
print('\n')

# check OrderStatus column
print('check OrderStatus column')
print('====')
print('Data format: ' + str(check_data_format(df, 'OrderStatus', 'A', [10])))
print('\n')

check SalesID column
====
Data format: True
Unique values: False
Is integer: True
> 0: True


check SalesDate column
====
Data format: True
Date format: False


check OrderID column
====
Data format: True
Is integer: True
>0: True


check CustomerID column
====
Data format: True
Is integer: True
> 0: True


check SalesPersonID column
====
Data format: True
Is integer: True
> 0: True


check ProductID column
====
Data format: False
Is integer: True
> 0: False


check Quantity column
====
Data format: True
Is integer: True
> 0: True


check Sales column
====
Data format: False
Is float: True
>= 0: True


check StoreID column
====
Data format: False


check OrderStatus column
====
Data format: False

Modify the function to also list the rows that do not comply with the specified validation rule:

In [15]:
def numerical_range_identify_non_complying_rows (df, column_name, lower_bound = - math.inf, upper_bound = math.inf): # returns a list of row(s) that do not comply to numerical range rule
  non_compliers = []
  for index in range(1, l + 1):
    value = df.loc[index][column_name]
    if value >= upper_bound or value <= lower_bound: # note that here we are using numerical operators
      non_compliers.append(df.loc[index])
  return non_compliers

*Define a helper function to print relevant rows neatly:*

In [16]:
def pprint_row_list (lis):
  for i in range(len(lis)):
    print('Item number ' + str(i + 1))
    print(lis[i])
    print('\n')

In [17]:
pprint_row_list(numerical_range_identify_non_complying_rows(df, 'ProductID', lower_bound = 0))

Item number 1
SalesID              1362
SalesDate        2/5/2020
OrderID             13723
CustomerID             28
SalesPersonID           4
ProductID             -77
Quantity                8
Sales               136.2
StoreID                 3
OrderStatus      Complete
Name: 1326, dtype: object


Item number 2
SalesID              3526
SalesDate        3/1/2021
OrderID             12694
CustomerID             34
SalesPersonID           9
ProductID             -19
Quantity               38
Sales               322.8
StoreID                 4
OrderStatus      Complete
Name: 2876, dtype: object


Item number 3
SalesID               2515
SalesDate        16/4/2021
OrderID              12228
CustomerID              51
SalesPersonID            1
ProductID              -18
Quantity                40
Sales               1107.1
StoreID                  8
OrderStatus       Complete
Name: 4814, dtype: object


Item number 4
SalesID              5755
SalesDate        1/6/2021
OrderID             14416
CustomerID             32
SalesPersonID           4
ProductID             -50
Quantity               21
Sales               348.8
StoreID                 6
OrderStatus      Complete
Name: 5498, dtype: object


Item number 5
SalesID              6145
SalesDate        1/7/2021
OrderID             12199
CustomerID             30
SalesPersonID           5
ProductID             -68
Quantity               14
Sales               153.7
StoreID                 9
OrderStatus      Complete
Name: 5924, dtype: object


Item number 6
SalesID              7587
SalesDate        2/9/2021
OrderID             15814
CustomerID             38
SalesPersonID           9
ProductID             -72
Quantity               12
Sales               131.8
StoreID                 4
OrderStatus      Complete
Name: 7443, dtype: object


Item number 7
SalesID                2813
SalesDate        17/11/2021
OrderID               16065
CustomerID               31
SalesPersonID             9
ProductID               -12
Quantity                  4
Sales                  39.6
StoreID                   5
OrderStatus        Complete
Name: 8227, dtype: object

Modify the rest of the relevant validation check functions to also return a list of non-complying rows:

In [18]:
def date_format_identify_non_complying_rows (df, column_name): # returns a list of row(s) that do not comply to date format rule
  non_compliers = []
  for row_index in range(1, l + 1): # going through the df row by row this time
    value_complies = True
    value = df.loc[row_index][column_name]
    value_split = value.split('/') # split each value into 3 parts to assess individually
    if int(value_split[0]) < 0 or int(value_split[0]) > 31: # reject if date is not int or date < 0 or date > 31
      value_complies = False
    if int(value_split[1]) < 0 or int(value_split[1]) > 12: # reject if month is not int or month < 0 or month > 12
      value_complies = False
    if len(value_split[2]) != 4 or not is_intable(value_split[2]): # reject if year is not int or year is not 4 digits
      value_complies = False
    if value_complies == False:
      non_compliers.append(df.loc[row_index])
  return non_compliers

def unique_values_identify_non_complying_rows (df, column_name): # returns a list of row(s) that do not comply to unique values rule
  non_compliers = []
  value_occurence_list = defaultdict(list) # defaultdict(list) defaults to an empty list ([]) for keys not yet added to the dictionary
  for index in range(1,l + 1): # remember l is len(df)
    value = df.loc[index][column_name]
    value_occurence_list[value].append(index)
  for value in value_occurence_list.keys():
    if len(value_occurence_list[value]) > 1:
      non_compliers = non_compliers + [df.loc[index] for index in value_occurence_list[value]]
  return non_compliers

def data_format_identify_non_complying_rows (df, column_name, character_type, pieces_max_lengths): # returns a list of row(s) that do not comply to data format rule
  non_compliers = []
  match character_type:
    case 'N':
      if len(pieces_max_lengths) == 2: # data format is N(p,q)
        for index in range(1, l + 1):
          val_str = str(df.loc[index][column_name])
          val_str_pieces = val_str.split('.')
          complies = is_intable(val_str_pieces[0]) and is_intable(val_str_pieces[1]) and len(val_str_pieces[0]) <= pieces_max_lengths[0] and len(val_str_pieces[1]) <= pieces_max_lengths[1]
          if not complies:
            non_compliers.append(df.loc[index])
        return non_compliers
      elif len(pieces_max_lengths) == 1: # data format is N(p)
        for index in range(1, l + 1):
          value = df.loc[index][column_name]
          complies = is_intable(value) and len(str(value)) <= pieces_max_lengths[0]
          if not complies:
            non_compliers.append(df.loc[index])
        return non_compliers
    case 'A': # data format is A(p)
      for index in range(1, l + 1):
          value = df.loc[index][column_name]
          complies = is_alphabetical(value) and len(value) <= pieces_max_lengths[0]
          if not complies:
            non_compliers.append(df.loc[index])
      return non_compliers
    case 'X': # data format is X(p)
      for index in range(1, l + 1):
          value = df.loc[index][column_name]
          complies = len(value) <= pieces_max_lengths[0]
          if not complies:
            non_compliers.append(df.loc[index])
      return non_compliers

Run the newly-modified functions on the rows to find the culprit rows:

In [19]:
print('Check SalesId column - non-unique values:')
pprint_row_list(unique_values_identify_non_complying_rows(df, 'SalesID'))
print('\n')

print('Check SalesDate column - date format:')
pprint_row_list(date_format_identify_non_complying_rows(df, 'SalesDate'))
print('\n')

print('Check ProductID column - data format:')
pprint_row_list(data_format_identify_non_complying_rows(df, 'ProductID', 'N', [2]))
print('\n')

print('Check Sales column - data format:')
pprint_row_list(data_format_identify_non_complying_rows(df, 'Sales', 'N', [10,2]))
print('\n')

Check SalesId column - non-unique values:
Item number 1
SalesID               372
SalesDate        2/1/2020
OrderID             14702
CustomerID             37
SalesPersonID           2
ProductID              36
Quantity               48
Sales               317.1
StoreID                 2
OrderStatus      Complete
Name: 193, dtype: object


Item number 2
SalesID               372
SalesDate        2/1/2020
OrderID             14702
CustomerID             37
SalesPersonID           2
ProductID              36
Quantity               48
Sales               317.1
StoreID                 2
OrderStatus      Complete
Name: 414, dtype: object


Item number 3
SalesID                 28
SalesDate        17/1/2020
OrderID              10519
CustomerID              37
SalesPersonID            9
ProductID               60
Quantity                10
Sales                 51.1
StoreID                  9
OrderStatus       Complete
Name: 427, dtype: object


Item number 4
SalesID                 28
SalesDate        17/1/2020
OrderID              10519
CustomerID              37
SalesPersonID            9
ProductID               60
Quantity                10
Sales                 51.1
StoreID                  9
OrderStatus       Complete
Name: 537, dtype: object


Item number 5
SalesID              1502
SalesDate        1/6/2020
OrderID             15318
CustomerID             21
SalesPersonID           3
ProductID              19
Quantity               17
Sales               176.1
StoreID                 8
OrderStatus      Complete
Name: 1450, dtype: object


Item number 6
SalesID              1502
SalesDate        1/6/2020
OrderID             15318
CustomerID             21
SalesPersonID           3
ProductID              19
Quantity               17
Sales               176.1
StoreID                 8
OrderStatus      Complete
Name: 1695, dtype: object


Item number 7
SalesID               2904
SalesDate        17/1/2021
OrderID              10862
CustomerID              44
SalesPersonID            7
ProductID               52
Quantity                 8
Sales                683.5
StoreID                  2
OrderStatus       Complete
Name: 3165, dtype: object


Item number 8
SalesID               2904
SalesDate        17/1/2021
OrderID              10862
CustomerID              44
SalesPersonID            7
ProductID               52
Quantity                 8
Sales                683.5
StoreID                  2
OrderStatus       Complete
Name: 6644, dtype: object




Check SalesDate column - date format:
Item number 1
SalesID               3160
SalesDate        4/14/2021
OrderID              13224
CustomerID              64
SalesPersonID            2
ProductID               51
Quantity                 7
Sales                797.3
StoreID                  4
OrderStatus       Complete
Name: 4809, dtype: object


Item number 2
SalesID               2622
SalesDate        9/30/2021
OrderID              13188
CustomerID              42
SalesPersonID            1
ProductID               16
Quantity                48
Sales                379.2
StoreID                  8
OrderStatus       Complete
Name: 7718, dtype: object




Check ProductID column - data format:
Item number 1
SalesID              1362
SalesDate        2/5/2020
OrderID             13723
CustomerID             28
SalesPersonID           4
ProductID             -77
Quantity                8
Sales               136.2
StoreID                 3
OrderStatus      Complete
Name: 1326, dtype: object


Item number 2
SalesID              3526
SalesDate        3/1/2021
OrderID             12694
CustomerID             34
SalesPersonID           9
ProductID             -19
Quantity               38
Sales               322.8
StoreID                 4
OrderStatus      Complete
Name: 2876, dtype: object


Item number 3
SalesID               2515
SalesDate        16/4/2021
OrderID              12228
CustomerID              51
SalesPersonID            1
ProductID              -18
Quantity                40
Sales               1107.1
StoreID                  8
OrderStatus       Complete
Name: 4814, dtype: object


Item number 4
SalesID              5755
SalesDate        1/6/2021
OrderID             14416
CustomerID             32
SalesPersonID           4
ProductID             -50
Quantity               21
Sales               348.8
StoreID                 6
OrderStatus      Complete
Name: 5498, dtype: object


Item number 5
SalesID              6145
SalesDate        1/7/2021
OrderID             12199
CustomerID             30
SalesPersonID           5
ProductID             -68
Quantity               14
Sales               153.7
StoreID                 9
OrderStatus      Complete
Name: 5924, dtype: object


Item number 6
SalesID              7587
SalesDate        2/9/2021
OrderID             15814
CustomerID             38
SalesPersonID           9
ProductID             -72
Quantity               12
Sales               131.8
StoreID                 4
OrderStatus      Complete
Name: 7443, dtype: object


Item number 7
SalesID                2813
SalesDate        17/11/2021
OrderID               16065
CustomerID               31
SalesPersonID             9
ProductID               -12
Quantity                  4
Sales                  39.6
StoreID                   5
OrderStatus        Complete
Name: 8227, dtype: object




Check Sales column - data format:
Item number 1
SalesID              5684
SalesDate        1/6/2021
OrderID             11400
CustomerID             32
SalesPersonID           1
ProductID              41
Quantity               13
Sales              70.139
StoreID                 1
OrderStatus      Complete
Name: 5427, dtype: object

Modify the functions again to provide a percentage of all rows that do not comply with the relevant data validation rule:

In [20]:
# returns the percentage of row(s) that do not comply to numerical range rule
def numerical_range_percentage_non_compliance (df, column_name, lower_bound = - math.inf, upper_bound = math.inf):
  return len(numerical_range_identify_non_complying_rows(df, column_name, lower_bound, upper_bound)) / l * 100

In [21]:
numerical_range_percentage_non_compliance(df, 'ProductID', lower_bound = 0)

0.08237232289950577

New function to check that all values in the column 'StoreID' fall contain only the permitted values (1 - 9) - generated by ChatGPT!

In [22]:
def check_store_id_quality(df):
    # Define the permitted values
    permitted_values = {1, 2, 3, 4, 5, 6, 7, 8, 9}

    # Filter rows where 'StoreID' is not in the permitted values
    invalid_rows = df[~df['StoreID'].isin(permitted_values)]

    # Return the invalid rows as a list of dictionaries
    return invalid_rows.to_dict(orient='records')

In [23]:
check_store_id_quality(df)

[{'SalesID': 584,
  'SalesDate': '1/2/2020',
  'OrderID': 11412,
  'CustomerID': 28,
  'SalesPersonID': 5,
  'ProductID': 24,
  'Quantity': 11,
  'Sales': 58.2,
  'StoreID': -2,
  'OrderStatus': 'Complete'},
 {'SalesID': 3355,
  'SalesDate': '2/1/2021',
  'OrderID': 15714,
  'CustomerID': 80,
  'SalesPersonID': 1,
  'ProductID': 29,
  'Quantity': 11,
  'Sales': 1259.2,
  'StoreID': 44,
  'OrderStatus': 'Complete'},
 {'SalesID': 6293,
  'SalesDate': '2/7/2021',
  'OrderID': 11554,
  'CustomerID': 39,
  'SalesPersonID': 3,
  'ProductID': 36,
  'Quantity': 46,
  'Sales': 350.5,
  'StoreID': 14,
  'OrderStatus': 'Complete'}]